services:
  - type: web
    name: aloysia-aio # All In One
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python code/main_aio.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
