services:
  - type: web
    name: aloysia-aio # All In One
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python code/telegram_bot.py & python -m streamlit run code/streamlit_app.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
